Repository scroll-tech/go-ethereum, pull requests merged in 2023-10, with the labels that each got.

#521 feat: configure max block range for eth_getLogs
  cmd/geth/main.go
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/config.go
  eth/ethconfig/gen_config.go
  eth/filters/api.go
  eth/filters/filter_system_test.go
  les/client.go
  params/version.go
Labels: feature

#522 fix(libzkp): upgrade libzkp to `v0.9.4` and add ccc `SetLightMode`
  core/block_validator.go
  miner/worker.go
  params/version.go
  rollup/circuitcapacitychecker/impl.go
  rollup/circuitcapacitychecker/libzkp/Cargo.lock
  rollup/circuitcapacitychecker/libzkp/Cargo.toml
  rollup/circuitcapacitychecker/libzkp/libzkp.h
  rollup/circuitcapacitychecker/libzkp/src/lib.rs
  rollup/circuitcapacitychecker/mock.go
  rollup/circuitcapacitychecker/types.go
Labels: breaking-change

#532 fix: use non-overlapping DB prefix for L1 messages
  cmd/utils/flags.go
  core/rawdb/database.go
  core/rawdb/schema.go
  params/version.go
Labels: breaking-change

#535 fix(libzkp): upgrade to use prover `v0.9.7`
  params/version.go
  rollup/circuitcapacitychecker/libzkp/Cargo.lock
  rollup/circuitcapacitychecker/libzkp/Cargo.toml
Labels: breaking-change

#537 fix: eth_estimateGas error in zero balance address
  internal/ethapi/api.go
  params/version.go
Labels: bug

#515 feat(rollup): sync finalized batches from L1
  cmd/geth/main.go
  cmd/utils/flags.go
  core/rawdb/accessors_rollup_event.go
  core/rawdb/accessors_rollup_event_test.go
  core/rawdb/schema.go
  eth/backend.go
  eth/ethconfig/config.go
  eth/ethconfig/gen_config.go
  go.mod
  go.sum
  params/config.go
  params/version.go
  rollup/rollup_sync_service/abi.go
  rollup/rollup_sync_service/abi_test.go
  rollup/rollup_sync_service/batch_header.go
  rollup/rollup_sync_service/block.go
  rollup/rollup_sync_service/chunk.go
  rollup/rollup_sync_service/l1client.go
  rollup/rollup_sync_service/l1client_test.go
  rollup/rollup_sync_service/rollup_sync_service.go
  rollup/rollup_sync_service/rollup_sync_service_test.go
  rollup/rollup_sync_service/testdata/blockTrace_02.json
  rollup/rollup_sync_service/testdata/blockTrace_03.json
  rollup/rollup_sync_service/testdata/blockTrace_04.json
  rollup/rollup_sync_service/testdata/blockTrace_05.json
  rollup/rollup_sync_service/testdata/commit_batch_transaction.json
  rollup/rollup_sync_service/testdata/commit_batch_tx.rlp
  rollup/sync_service/types.go
Labels: feature
